### ISSUE TITLE
Support suppressing of rake's backtrace. 

### ISSUE THREAD

**Issue by ainame** [ainame/motion-mode#10]
When I use "motion-execute-rake" and then I sent SIGINT to iOS simulator, rake print flood of backtrace on STDOUT.
Such as following:

``` sh
     Build ./build/iPhoneSimulator-6.1-Development
  Simulate ./build/iPhoneSimulator-6.1-Development/promotion-sample.app
(main)>   C-c C-crake aborted!
Command failed with status (1): [DYLD_FRAMEWORK_PATH="/Applications/Xcode.a...]
/Users/namai/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.4/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/Users/namai/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `call'

.......................

/Users/namai/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/Users/namai/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/namai/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
```

I think that "--suppress-backtrace" which is rake's command line option will suppress that backtrace, but I insert that option in "motion-execute-rake", such as following:
  (pop-to-buffer (make-comint motion-execute-rake-buffer "rake" nil "--suppress-backtrace" "\".*\"" ))
then it options don't be validly processed.

Help me!!

**Comment by syohex** [comment]
```
(make-comint motion-execute-rake-buffer "rake" nil "--suppress-backtrace" "\".*\"" ))
```

Is double quote in last argument(PATTERN) needed ?
I think it should be `.*`. `\".*\"` may match double quoted stuff, such as `"hoge"`, not `hoge`.

Please try to use `.*` instead of `\".*\"`.
(Sorry I can't test it, because I don't have ruby motion).

**Comment by ainame** [comment]
@syohex thx!! I got suppressing backtrace! I will implement it soon.
